# Generated by Django 4.2 on 2023-04-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('den', models.IntegerField()),
                ('respuesta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('operacion', models.CharField(max_length=1)),
                ('num1', models.IntegerField()),
                ('den1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('den2', models.IntegerField()),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=60)),
                ('grado', models.IntegerField()),
                ('grupo', models.CharField(max_length=1)),
                ('num_lista', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('puntaje', models.IntegerField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='nivel',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.pregunta'),
        ),
    ]
